---

# failover.yml

# enforce that the primary environment is shut-down because maybe only one of the components is not available but, ignore if we can't connect to them as the server might not be available
- hosts: go-server-primary
  gather_facts: no
  ignore_unreachable: true
  tasks:
    - name: stop the primary go-server
      command: sudo /etc/init.d/go-server stop
      register: current_rc_1
      failed_when: current_rc_1.rc > 1
